.ifndef KRNL_GETIN
; Kernal
KRNL_GETIN          = $FFE4
KRNL_CHROUT         = $FFD2

KRNL_MEM_FILL		= $FEE4
KRNL_MEM_COPY       = $FEE7
KRNL_MEM_DECOMPRESS	= $FEED

KRNL_SETLFS   		= $FFBA
KRNL_SETNAM  		= $FFBD
KRNL_LOAD     		= $FFD5
KRNL_SAVE     		= $FFD8

KRNL_SCREEN   		= $FFED
KRNL_PLOT     		= $FFF0

KRNL_ERR_TOO_MANY_FILES			= $01
KRNL_ERR_FILE_OPEN				= $02
KRNL_ERR_FILE_NOT_OPEN			= $03
KRNL_ERR_FILE_NOT_FOUND			= $04
KRNL_ERR_DEVICE_NOT_PRESENT		= $05
KRNL_ERR_NOT_INPUT_FILE			= $06
KRNL_ERR_NOT_OUTPUT_FILE		= $07
KRNL_ERR_MISSING_FILENAME		= $08
KRNL_ERR_ILLEGAL_DEVICE_NUMBER	= $09

KEY_A 			= 65
KEY_Q 			= 81

KEY_CRSR_LEFT 	= 157
KEY_CRSR_RIGHT 	= 94
KEY_CRSR_UP 	= 95
KEY_CRSR_DOWN 	= 145

CHR_NL = 13
CHR_RETRUN = CHR_NL
CHR_CLEAR = 147
CHR_COLOR_WHITE = 5
CHR_COLOR_RED = 28
CHR_COLOR_GREEN = 30



IRQVec            	= $0314
.endif