; Sprite speech_big, frame 0 (64x32 - 16 colors)
sprite_speech_big_0:
.byte 0, 0	; x- and y-offset
.word 982+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 1 (64x32 - 16 colors)
sprite_speech_big_1:
.byte 0, 0	; x- and y-offset
.word 1014+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 2 (64x32 - 16 colors)
sprite_speech_big_2:
.byte 0, 0	; x- and y-offset
.word 1046+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 3 (64x32 - 16 colors)
sprite_speech_big_3:
.byte 0, 0	; x- and y-offset
.word 1078+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 4 (64x32 - 16 colors)
sprite_speech_big_4:
.byte 0, 0	; x- and y-offset
.word 1110+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 5 (64x32 - 16 colors)
sprite_speech_big_5:
.byte 0, 0	; x- and y-offset
.word 1142+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 6 (64x32 - 16 colors)
sprite_speech_big_6:
.byte 0, 0	; x- and y-offset
.word 1174+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 7 (64x32 - 16 colors)
sprite_speech_big_7:
.byte 0, 0	; x- and y-offset
.word 1206+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 8 (64x32 - 16 colors)
sprite_speech_big_8:
.byte 0, 0	; x- and y-offset
.word 1238+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_big, frame 9 (64x32 - 16 colors)
sprite_speech_big_9:
.byte 0, 0	; x- and y-offset
.word 1270+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_64+0	;h, w, palette index

; Sprite speech_medium, frame 0 (32x32 - 16 colors)
sprite_speech_medium_0:
.byte 0, 0	; x- and y-offset
.word 1302+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

; Sprite speech_medium, frame 1 (32x32 - 16 colors)
sprite_speech_medium_1:
.byte 0, 0	; x- and y-offset
.word 1318+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

; Sprite speech_medium, frame 2 (32x32 - 16 colors)
sprite_speech_medium_2:
.byte 0, 0	; x- and y-offset
.word 1334+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

; Sprite speech_medium, frame 3 (32x32 - 16 colors)
sprite_speech_medium_3:
.byte 0, 0	; x- and y-offset
.word 1350+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

; Sprite speech_medium, frame 4 (32x32 - 16 colors)
sprite_speech_medium_4:
.byte 0, 0	; x- and y-offset
.word 1366+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

; Sprite speech_medium, frame 5 (32x32 - 16 colors)
sprite_speech_medium_5:
.byte 0, 0	; x- and y-offset
.word 1382+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

; Sprite speech_small, frame 0 (32x32 - 16 colors)
sprite_speech_small_0:
.byte 0, 0	; x- and y-offset
.word 1398+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

; Sprite speech_small, frame 1 (32x32 - 16 colors)
sprite_speech_small_1:
.byte 0, 0	; x- and y-offset
.word 1414+VERA_sprite_colors_16	; address/32 (+ color indicator) 
.word 0, 0	; x,y pos
.byte VERA_sprite_layer_foreground	; 4 bit Collision mask, 3 bit z-depth, VFlip HFlip
.byte VERA_sprite_height_32+VERA_sprite_width_32+0	;h, w, palette index

